# Generated by Django 6.0.4 on 2026-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paid_at_order_updated_at_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
    ]
