# Generated by Django 6.0.4 on 2026-04-09 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverystatus',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=20),
        ),
    ]
